---
- name: Add Oracle Java repo
  apt_repository: repo='ppa:webupd8team/java'
- name: Accept oracle license
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
- name: Install java installer
  apt: pkg=oracle-java7-installer  state=latest