---

galaxy_info:
  author: kosssi
  description: Install phpStorm.
  min_ansible_version: 1.4
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
  - development
  - web
dependencies: []
